const availableTopics = [
	'Anime',
	'Art',
	'Baking',
	'Barbecuing',
	'Board game nights',
	'Board games',
	'Books',
	'Cake decorating',
	'Camping',
	'Card game tournaments',
	'Cartoons',
	'Cat breeds',
	'Celebrities',
	'Cocktails',
	'Coffee culture',
	'Comic books',
	'Concert experiences',
	'Cooking',
	'Cosplay',
	'Craft beer',
	'Cycling',
	'DIY projects',
	'Dance',
	'Dessert recipes',
	'Director filmographies',
	'Dog breeds',
	'Eco-friendly travel tips',
	'Esports tournaments',
	'European getaways',
	'Exotic pets',
	'Fashion',
	'Fashion accessories',
	'Fashion icons',
	'Fashion trends',
	'Fashion trends',
	'Film awards',
	'Fitness',
	'Food',
	'Food trucks',
	'Game streaming platforms',
	'Gaming communities',
	'Gaming consoles',
	'Gaming peripherals',
	'Gardening',
	'Hairstyle ideas',
	'Hiking',
	'Ice cream flavors',
	'Instrument tutorials',
	'Karaoke',
	'Makeup',
	'Makeup tutorials',
	'Memes',
	'Movie franchises',
	'Movie genres',
	'Movie soundtracks',
	'Movies',
	'Music',
	'Music festivals',
	'Music genres',
	'Music production software',
	'Music streaming platforms',
	'Nail art designs',
	'Online multiplayer games',
	'Outdoor activities',
	'Pet accessories',
	'Pet grooming',
	'Pet training tips',
	'Pets',
	'Photography',
	'Picnics',
	'Podcasts',
	'Potluck dinners',
	'Reality TV shows',
	'Retro gaming',
	'Road trips',
	'Rock climbing',
	'Rollerblading',
	'Running',
	'Skateboarding',
	'Skiing',
	'Smoothie combinations',
	'Snowboarding',
	'Social media influencers',
	'Sports',
	'Stand-up comedy',
	'Surfing',
	'Sustainable fashion brands',
	'Tea varieties',
	'Television',
	'Theater',
	'Travel',
	'Travel bucket list destinations',
	'Travel photography',
	'Travel souvenirs',
	'Tropical vacations',
	'Video game genres',
	'Video games',
	'Wine tasting',
	'YouTube channels',
];

export default availableTopics;
